public class PassengerWrapper {

    @AuraEnabled
    public String title;

    @AuraEnabled
    public String firstName;

    @AuraEnabled
    public String lastName;

    @AuraEnabled
    public Date dateOfBirth;

    @AuraEnabled
    public String gender;

    @AuraEnabled
    public String passengerType;

    @AuraEnabled
    public String passportNumber;

    @AuraEnabled
    public String mealPreference;

    @AuraEnabled
    public String email;

    @AuraEnabled
    public String phone;

}